# Generated by Django 5.0.1 on 2024-01-26 11:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contact',
            name='time_added',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
